### ISSUE TITLE
ClassNotFoundException: com.banzaicloud.spark.metrics.sink.PrometheusSink

### ISSUE THREAD

**Issue by tisy** [banzaicloud/spark-metrics#28]
Hello,
I'm really interested in using the library but currently I'm failing to use it in emr/yarn. It is giving a `ClassNotFoundException: com.banzaicloud.spark.metrics.sink.PrometheusSink` error.
I have tried including the jar in my fat jar but that does not help.
Here is the complete stack trace:

` Uncaught exception: java.lang.ClassNotFoundException: com.banzaicloud.spark.metrics.sink.PrometheusSink
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:198)
at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:194)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
at org.apache.spark.metrics.MetricsSystem.registerSinks(MetricsSystem.scala:194)
at org.apache.spark.metrics.MetricsSystem.start(MetricsSystem.scala:102)
at org.apache.spark.deploy.yarn.ApplicationMaster.createAllocator(ApplicationMaster.scala:454)
at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:481)
at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:773)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:772)
at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:797)
at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala) `

**Comment by stoader** [comment]
Does this happen in your local dev env as well? I'm trying to understand if this has to do with the environment on EMR.  Also can you check all the other jars listed here: https://github.com/banzaicloud/spark-metrics/blob/master/PrometheusSink.md are available on the classpath?

**Comment by tisy** [comment]
Just tried: it works in local mode.
Seems like it is when running in Yarn that it does not work.
Thoughts ?

**Comment by stoader** [comment]
can you verify that all the necessary jars (containing io.prometheus:simpleclient:0.3.0,io.prometheus:simpleclient_dropwizard:0.3.0,io.prometheus:simpleclient_pushgateway:0.3.0,io.dropwizard.metrics:metrics-core:3.1.2) are available on the classpath under Yarn?

**Comment by tisy** [comment]
I added all those dependencies in the fat jar.

**Comment by stoader** [comment]
- can you check logs to see if the classpath contains the fat jar and that the jar actually was uploaded to the right classpath location?

- can you also give it a try to `--packages com.banzaicloud:spark-metrics_2.11:2.3-2.0.1,io.prometheus:simpleclient:0.3.0,io.prometheus:simpleclient_dropwizard:0.3.0,io.prometheus:simpleclient_pushgateway:0.3.0,io.dropwizard.metrics:metrics-core:3.1.2 --packages com.banzaicloud:spark-metrics_2.11:2.3-2.0.1,io.prometheus:simpleclient:0.3.0,io.prometheus:simpleclient_dropwizard:0.3.0,io.prometheus:simpleclient_pushgateway:0.3.0,io.dropwizard.metrics:metrics-core:3.1.2` instead of using a fat jar?

**Comment by tisy** [comment]
- Yes, classpath contains the fat jar. Indeed my app is also in the fat jar and Yarn finds it.
- Yes, that's the first thing I tried as per the documentation.

Did you have a chance to try on Yarn ?

**Comment by stoader** [comment]
We are not running Spark on Yarn but on Kubernetes.  The `com.banzaicloud.spark.metrics.sink.PrometheusSink` class has no special requirement regarding classloading so it's weird that it doesn't load on Yarn. The only thing I can imagine that Yarn has its own class loader which is not able to load this class.

**Comment by tisy** [comment]
Hi,
Sorry for late replay. I was still struggling with this.
Finally I managed to get it work in yarn cluster mode.
You don't need/have to enable the sink in the workers. Just driver is sufficient, because metrics are forwarded from workers do driver (see here: http://apache-spark-user-list.1001560.n3.nabble.com/Custom-Metric-Sink-on-Executor-Always-ClassNotFound-td34205.html#a34206).
So you have to set 
`driver.sink.prometheus.class=com.banzaicloud.spark.metrics.sink.PrometheusSink`
insatead of:
`*.sink.prometheus.class=com.banzaicloud.spark.metrics.sink.PrometheusSink`
Then the sink is not needed in the workers and you get all your metrics.

Thank you for the good work !

**Comment by stoader** [comment]
@tisy thank you for sharing the solution. I'm closing this GH issue.

**Comment by chrilves** [comment]
> So you have to set
> `driver.sink.prometheus.class=com.banzaicloud.spark.metrics.sink.PrometheusSink`
> insatead of:
> `*.sink.prometheus.class=com.banzaicloud.spark.metrics.sink.PrometheusSink`
> Then the sink is not needed in the workers and you get all your metrics.

Thank you so so so so much (yes that much!!). I was about to lose any hope.

**Comment by GezimSejdiu** [comment]
Hi @tisy , 

thanks a lot for this hint and @stoader for great work with spark-metrics.

b.t.w  when you say:

> Actually, you don't need/have to enable the sink in the workers in yarn cluster mode. Just driver is sufficient, because metrics are forwarded from workers to the driver.

Do you also get metrics i.e. for the executor on the Pushgateway? or only with the `role=driver`? It would be good if you can elaborate a bit on what do you mean by forwarding from workers to the driver? Do they get summed up and shown on the driver only? One good example is also to see which of the workers/executors is having issues with the workload or specific executor metrics e.g. `app-00000.jvm.threadpool.activeTasks` but if they are summed up already on the driver then it should be enough for the Spark application metrics.

Best regards,
