### ISSUE TITLE
No Metrics From Spark Executors (Classes are being instantiated)

### ISSUE THREAD

**Issue by julianblack** [banzaicloud/spark-metrics#63]
I am receiving metrics from the Spark driver.  I can see the PrometheusSink class being initialized on the Spark executor but nothing is showing up in the pushgateway.  

I also don't see any logs/reason why it wouldn't be pushing, even though I have logs at DEBUG level. 

Here is my executor logs:
``` 
2020-08-12 20:26:05,522 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - Initializing Prometheus Sink...
2020-08-12 20:26:05,522 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - Metrics polling period -> 30 SECONDS
2020-08-12 20:26:05,523 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - Metrics timestamp enabled -> false
2020-08-12 20:26:05,523 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - pushgateway-address -> services-xxxx/xxxxx-pushgateway-dev
2020-08-12 20:26:05,523 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - pushgateway-address-protocol -> https
2020-08-12 20:26:05,523 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - metrics-name-capture-regex -> 
2020-08-12 20:26:05,524 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - metrics-name-replacement -> 
2020-08-12 20:26:05,525 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - labels -> Map()
2020-08-12 20:26:05,525 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - jmx-collector-config -> jmxCollector.yaml
```

```
2020-08-12 20:26:35,686 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - metricsNamespace=None, sparkAppName=Some(nokia-sps-decoder-Spark), sparkAppId=Some(application_1584132323547_997813), executorId=Some(6)
2020-08-12 20:26:35,687 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - role=executor, job=application_1584132323547_997813
```

Is there a way I can get more information on why this isn't working? ie. more verbose logs
I've provided my other related configurations as reference below.  

Spark Submit:
```
spark2-submit --master=yarn \
    --deploy-mode=cluster \
    --conf "spark.executor.extraClassPath=spark-metrics_2.11-2.4-1.0.5.jar:metrics-core-3.1.2.jar:simpleclient-0.8.1.jar:simpleclient_dropwizard-0.8.1.jar:simpleclient_pushgateway-0.8.1.jar:simpleclient_common-0.8.1.jar:collector-0.12.0.jar:slf4j-api-1.7.16.jar:guava-26.0-android.jar" \
    --conf "spark.driver.extraClassPath=spark-metrics_2.11-2.4-1.0.5.jar:metrics-core-3.1.2.jar:simpleclient-0.8.1.jar:simpleclient_dropwizard-0.8.1.jar:simpleclient_pushgateway-0.8.1.jar:simpleclient_common-0.8.1.jar:collector-0.12.0.jar:slf4j-api-1.7.16.jar:guava-26.0-android.jar" \
	--executor-memory 4G \
    --num-executors 5 \
    --driver-memory 4G \
    --executor-cores 4 \
	--conf spark.yarn.queue=root.high \
	--files "Config/DEV.ini,Build/src/main/resources/kafka-DEV.jaas,${USRENV},Build/src/main/resources/metrics-prod.properties,/xxxx/truststore.jks,Build/src/main/resources/jmxCollector.yaml,Build/src/main/resources/log4j.properties" \
	--class xxxxx.ProcessStream \
    --jars hdfs://nameservice1/Common/Code/Lib/FOX/Alarming/v2/fox-alarming-v2.jar,spark-metrics_2.11-2.4-1.0.5.jar,metrics-core-3.1.2.jar,simpleclient-0.8.1.jar,simpleclient_dropwizard-0.8.1.jar,simpleclient_pushgateway-0.8.1.jar,simpleclient_common-0.8.1.jar,collector-0.12.0.jar,slf4j-api-1.7.16.jar,guava-26.0-android.jar \
    --conf "spark.metrics.conf=metrics-prod.properties" \
	--conf "spark.driver.extraJavaOptions=-Djavax.net.ssl.trustStore=truststore.jks -Djavax.net.ssl.trustStorePassword=xxxx-Dspark.metrics.conf=metrics-prod.properties -Dlog4j.configuration=log4j.properties" \
	--conf "spark.executor.extraJavaOptions=-Djavax.net.ssl.trustStore=truststore.jks -Djavax.net.ssl.trustStorePassword=xxxx-Dspark.metrics.conf=metrics-prod.properties -Dlog4j.configuration=log4j.properties" \
	--conf spark.executor.memoryOverhead=5G \
    --conf spark.driver.memoryOverhead=5G \
	Build/target/nokia-sps-decoder-jar-with-dependencies.jar DEV.ini kafka-DEV.jaas
```

metrics-prod.properties
```
# Enable Prometheus for all instances by class name
*.sink.prometheus.class=org.apache.spark.banzaicloud.metrics.sink.PrometheusSink
# Prometheus pushgateway address
*.sink.prometheus.pushgateway-address-protocol=https
*.sink.prometheus.pushgateway-address=services-xxxxx/xxxx-pushgateway-dev
*.sink.prometheus.period=30
*.sink.prometheus.unit=seconds
*.sink.prometheus.pushgateway-enable-timestamp=false
# Support for JMX Collector (version 2.3-2.0.0 +)
*.sink.prometheus.enable-dropwizard-collector=false
*.sink.prometheus.enable-jmx-collector=true
*.sink.prometheus.jmx-collector-config=jmxCollector.yaml
# Enable HostName in Instance instead of Appid (Default value is false i.e. instance=${appid})
*.sink.prometheus.enable-hostname-in-instance=true
# Enable JVM metrics source for all instances by class name
*.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink
*.source.jvm.class=org.apache.spark.metrics.source.JvmSource
```

jmxCollector.yaml
```
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["*:*"]
```

Pushgateway UI: 
![image](https://user-images.githubusercontent.com/37048453/90134640-755e1680-dd3f-11ea-83b9-b8d94accff61.png)

I'd really appreciate any guidance, as it stands I won't be able to use the library without the executor metrics :(

Thanks!

**Comment by stoader** [comment]
These log lines:
```
2020-08-12 20:26:35,686 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - metricsNamespace=None, sparkAppName=Some(nokia-sps-decoder-Spark), sparkAppId=Some(application_1584132323547_997813), executorId=Some(6)
2020-08-12 20:26:35,687 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - role=executor, job=application_1584132323547_997813
```
 indicate that metrics are being pushed by the sink to Pushgateway so this doesn't seem to be a `spark-metrics` issue.

If you want to debug what payload spark-metrics sends to pushgateway than reconfigure your spark-mertics to send metrics to something like netcat (e.g. provide the address and port of a netcat as *.sink.prometheus.pushgateway-address and *.sink.prometheus.pushgateway-address-protocol=http

Also, worth checking Pushgateway logs as well.

**Comment by julianblack** [comment]
Thanks for responding.  You're right when I use netcat from a Hadoop edge node, using HTTP protocol, I'm seeing all the executor metrics.  

Unfortunately though, this doesn't help me troubleshoot why it wouldn't be working to a remote HTTPS pushgateway on the executors only.  

There is no mention of the `role=executor` in the pushgateway logs, so it doesn't seem to be getting there.  

Is it possible it could be an SSL certificate or connectivity issue?  
Is there a way to print these types of exceptions if that is the case?  
Does the plugin work with HTTPS?

Again, I really appreciate your input.

**Comment by stoader** [comment]
if there were SSL related errors it would be visible in the logs, also the driver metrics would affected as well.

If you capture the executor metrics  with netcat and than push those to pushgateway using `curl`, through https, from one of the executor nodes, do those metrics make through?

**Comment by julianblack** [comment]
Hi @stoader , I just tested this and yes it works through curl after I paste the netcat output into a file.

Manual curl commands:
```
cat push_load_1.txt | curl --silent --data-binary @- "https://xxxx/xxx-pushgateway-qa/metrics/job/application_1584132323547_1018676/role/driver/app_name/nokia-sps-decoder-Spark/instance/xxxx" 

cat push_load_2.txt | curl --silent --data-binary @- "https://xxxx/xxxx-pushgateway-qa/metrics/job/application_1584132323547_1018676/role/executor/app_name/nokia-sps-decoder-Spark/instance/xxxx/number/3" 
```

Sample executor payload (push_load_2.txt):
![image](https://user-images.githubusercontent.com/37048453/90432477-92c11680-e098-11ea-8844-dffaba36d95a.png)

Pushgateway UI:
![image](https://user-images.githubusercontent.com/37048453/90432210-33fb9d00-e098-11ea-8c15-828ea92211c8.png)

**Comment by stoader** [comment]
did you run the curl command from the executor node or from your dev machine?

**Comment by julianblack** [comment]
From my dev machine, to verify the payload format. But I can also try it from a data node.

**Comment by julianblack** [comment]
Its also worth noting I spun up a different pushgateway instance, in a separate kubernertes cluster and seeing same behavior when plugin is pushing the data.

**Comment by julianblack** [comment]
@stoader just to cover all bases here. I am passing the jars above seen in the original post.  Are these the correct dependencies? 
(version wise).  

I also noticed when I removed the `truststore.jks` from the driver, I didn't receive an error message, and the stats were not pushed to the pushgateway.  (Same behavior I'm seeing on the executors.) Do you know why I wouldnt be seeing an error message? I think if we can figure the logging, it will give us more insight to the issue on the executors.  (Potentially SSL-related).

Thanks,

**Comment by julianblack** [comment]
Alright scratch that last comment.  I do see this error on the driver:
```
2020-08-17 15:48:45,581 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - metricsNamespace=None, sparkAppName=Some(nokia-sps-decoder-Spark), sparkAppId=Some(application_1584132323547_1019351), executorId=Some(driver)
2020-08-17 15:48:45,581 INFO [org.apache.spark.banzaicloud.metrics.sink.PrometheusSink] - role=driver, job=application_1584132323547_1019351
2020-08-17 15:48:45,582 ERROR [org.apache.spark.util.Utils] - Uncaught exception in thread Thread-5
java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:248)
	at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:255)
	at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:405)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:305)
	at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:182)
	at com.banzaicloud.spark.metrics.sink.PrometheusSink$Reporter.report(PrometheusSink.scala:98)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:162)
	at com.banzaicloud.spark.metrics.sink.PrometheusSink.report(PrometheusSink.scala:233)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$report$1.apply(MetricsSystem.scala:116)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$report$1.apply(MetricsSystem.scala:116)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.metrics.MetricsSystem.report(MetricsSystem.scala:116)
	at org.apache.spark.SparkContext$$anonfun$stop$3.apply$mcV$sp(SparkContext.scala:1938)
	at org.apache.spark.util.Utils$.tryLogNonFatalError(Utils.scala:1385)
	at org.apache.spark.SparkContext.stop(SparkContext.scala:1937)
	at org.apache.spark.SparkContext$$anonfun$2.apply$mcV$sp(SparkContext.scala:575)
	at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:216)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:188)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1990)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply$mcV$sp(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:188)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:188)
	at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:178)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
```

**Comment by julianblack** [comment]
@stoader I've solved the issue. It was an SSL issue on the executors.  My `extraJavaOptions` were being overwritten at the application level.  Though as seen above, the plugin logs the SSL issue on the driver, but not on the executors. It might help to have these logs for troubleshooting at the executor level.  Anyways thanks for all the help! Awesome plugin to extract metrics.
